(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const example = '比较 App A 和 App B 的训练计划功能，整理差异和待核实项';
  const states = {a:{stage:'input',question:example,tab:'report',step:0,follow:''},b:{stage:'input',question:example,tab:'report',step:0,follow:''}};
  let layout = new URLSearchParams(location.search).get('layout') === 'b' ? 'b' : 'a';
  let timer, runTimer, pickerBackup=null;
  let libraryOpen=false, catalogQuery='', catalogGroup='全部';
  for (const x of Object.values(states)) {x.routing='auto';x.selected=['web'];x.required=['web'];x.skipped=[];}
  const groups=['全部',...new Set(capabilityCatalog.map(x=>x.group))];
  const cap=id=>capabilityCatalog.find(x=>x.id===id);
  const selectionText=()=>state().routing==='auto'?'自动匹配来源':`已指定 ${state().selected.length} 个来源`;
  function openPicker(){saveInputs();pickerBackup={routing:state().routing,selected:[...state().selected],required:[...state().required]};drawPicker();$('source-picker').showModal()}
  function drawPicker(){const s=state();$('picker-content').innerHTML=`<h2 id="picker-title">这次研究去哪里找？</h2><p class="dialog-hint">默认只在可用且已授权的能力中选择。指定为必需的来源不可被静默替代。</p><div class="route-options"><button class="outline ${s.routing==='auto'?'selected':''}" data-route="auto">自动匹配</button><button class="outline ${s.routing==='manual'?'selected':''}" data-route="manual">我指定来源</button></div><p class="mock-label">本草稿只有公开网页的固定虚构资料；其他来源选择仅用于体验缺口处理。</p><label class="catalog-search">搜索本次需要的来源<input id="picker-query" placeholder="平台名，例如小红书"></label><div class="picker-options">${capabilityCatalog.map(x=>`<div class="picker-row" data-pick-row="${x.name}"><label><input type="checkbox" data-pick="${x.id}" ${s.selected.includes(x.id)?'checked':''}> <b>${x.name}</b><small>${x.ready?'演示可用':'规划 · 未接入'}</small></label>${s.selected.includes(x.id)?`<label class="required-choice"><input type="checkbox" data-required="${x.id}" ${s.required.includes(x.id)?'checked':''}> 必需</label>`:''}</div>`).join('')}</div><p class="dialog-hint">“必需”缺失时暂停；非必需来源不可用时，可先交付其余资料并列出缺口。选择来源不会安装工具或登录。</p><div class="picker-footer"><button class="text-button" data-action="catalog">查看全部能力与配置 →</button><button class="solid" data-action="apply-sources">使用此范围</button></div>`}
  function library(){return `<section class="catalog-page"><div class="eyebrow">SOURCE CENTER / 能力目录</div><h1>平台可以增加，研究方式不必变。</h1><p class="subtitle">任务里选择资料范围，在这里管理连接与操作能力。</p><div class="catalog-stats"><span><b>${capabilityCatalog.length}</b> 个上游目录条目</span><span><b>${capabilityCatalog.filter(x=>x.ready).length}</b> 个演示可用来源</span><span><b>0</b> 次本轮连接检测</span></div><div class="catalog-notice">目录依据 Agent-Reach 2026-09-26 上游说明整理，不代表本产品已接入全部平台。原工作台已接通网页搜索和读取；这里的状态仅属于独立交互草稿，不是本机安装清单。此页不读取凭据、不检测登录、不安装工具。接入方式和真实健康状态将在后端连接后展示。</div><label class="catalog-search">搜索平台或能力<input id="catalog-query" placeholder="例如：小红书、字幕、评论" value="${esc(catalogQuery)}"></label><nav class="catalog-filters" aria-label="来源分类">${groups.map(g=>`<button data-group="${g}" aria-pressed="${catalogGroup===g}">${g}</button>`).join('')}</nav><div id="catalog-results">${catalogCards()}</div><p class="dialog-hint">已连接、需登录、部分可用、暂时失败将按具体操作显示。新渠道通过能力目录注册，不新增一级导航。发布、评论、提交 PR 等写操作不在资料研究入口内。</p></section>`}
  function catalogCards(){const found=capabilityCatalog.filter(x=>(catalogGroup==='全部'||x.group===catalogGroup)&&[x.name,x.purpose,...x.ops].join(' ').toLowerCase().includes(catalogQuery.toLowerCase()));return `<div class="catalog-grid">${found.map(x=>`<article class="cap-card"><div class="cap-head"><h2>${x.name}</h2><span class="${x.ready?'available':'planned'}">${x.ready?'演示可用':'未接入'}</span></div><p>${x.purpose}</p><div class="cap-ops">${x.ops.map(op=>`<span>${op}</span>`).join('')}</div><small>${x.auth||'实际可用范围待逐项验证'}</small><button class="text-button" data-capability="${x.id}">能力与接入要求 ↗</button></article>`).join('')||'<p>没有匹配项，试试“字幕”或“评论”。</p>'}</div>`}
  function acquisitionStatus(){const s=state();return `<details class="task-sources" open><summary>本次资料范围 · ${s.selected.length} 个来源</summary>${s.selected.map(id=>{const x=cap(id);return `<div><b>${x.name}</b><small>${s.required.includes(id)?'必需':'可选'} · ${x.ready?(s.stage==='done'?'4 份虚构资料':'演示可用'):(s.skipped.includes(id)?'已跳过 · 未接入':'未接入')}</small></div>`}).join('')}<button class="text-button" data-action="sources">调整本次来源</button></details>`}
  function blocked(){const s=state();return `<div class="blocked-card"><span class="status-badge">需要处理 · 来源缺失示例</span><h2>必需资料还无法获取</h2><p>${s.selected.filter(id=>s.required.includes(id)&&!cap(id).ready).map(id=>cap(id).name).join('、')}尚未接入。普通网页不能替代指定平台的用户评价。</p><p class="dialog-hint">后续若只是登录失效，这里会提供“去本机处理登录 → 重新检查并继续”，保留此前已取得的证据。</p><div class="exports"><button class="outline" data-action="catalog">查看接入要求</button><button class="outline" data-action="sources">调整资料范围</button><button class="text-button" data-action="cancel">取消任务</button></div><small>本草稿不模拟成功登录，也不生成小红书评价。</small></div>`}
  function scheduleDemo(){clearTimeout(runTimer);if(layout!=='a'||libraryOpen||state().stage!=='running')return;runTimer=setTimeout(()=>{if($('source-picker').open){scheduleDemo();return}state().step++;if(state().step>=3){state().stage='done';state().step=4;}render();scheduleDemo()},2600)}

  const steps = ['获取公开资料','整理分析初稿','独立复核与修正','交付报告'];
  const sources = {
    S1:{title:'App A · 训练计划帮助说明',quote:'可在训练页创建计划，并调整每周训练日。',date:'未知',version:'未说明'},
    S2:{title:'App B · 训练计划功能介绍',quote:'用户可以选择现有训练计划，并查看每周训练安排。',date:'未知',version:'未说明'},
    S3:{title:'App A · 使用范围说明',quote:'不同地区和版本的服务可能有所差异，请以客户端实际展示为准。',date:'未知',version:'未列出具体范围'},
    S4:{title:'App B · 常见问题',quote:'本文介绍计划页面的基础操作。',date:'未知',version:'未说明'}
  };
  const state = () => states[layout];
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,3500)}
  function info(title,html){$('info-content').innerHTML=`<span class="eyebrow">交互草稿 / 不执行真实操作</span><h2 id="info-title">${title}</h2>${html}`;$('info').showModal()}
  function top(){return `<header class="page-top"><div class="crumb">研究空间 <span> / </span> <b>${libraryOpen?'来源中心':state().stage==='input'?'新建研究':'训练计划功能对比'}</b></div><div class="page-actions"><span class="mode-note">${layout==='a'?'A · 对话与报告在同一空间':'B · 一步一页，聚焦当前阶段'}</span>${libraryOpen?'<button data-action="return-task">← 返回当前任务</button>':'<button data-action="jump">直接体验结果 ↗</button>'}</div></header>`}
  function input(){return `<div class="start-screen"><div class="eyebrow">FROM QUESTION TO EVIDENCE</div><h1>让一个问题，<br>变成一份<em>有依据的答案。</em></h1><p class="subtitle">说出你想了解什么，其余交给研究流程。</p><form id="research-form"><div class="composer"><label for="question">研究问题</label><textarea id="question" maxlength="2000" required placeholder="输入研究问题，或粘贴你希望整理的公开链接">${esc(state().question)}</textarea><div class="compose-options"><button type="button" class="chip on" data-action="sources">◉ ${selectionText()} ⌄</button><button type="button" class="chip" data-action="scope" aria-expanded="false">研究范围 ⌄</button><span class="mock-label">演示任务</span></div><div id="scope-fields" class="scope" hidden><label>地区<input id="region" placeholder="不限" value="${esc(state().region||'')}"></label><label>时间<input id="period" placeholder="不限" value="${esc(state().period||'')}"></label></div><div class="compose-bottom"><small>本草稿只展示固定样例，不处理真实问题</small><button class="solid" type="submit">开始研究 <span>↗</span></button></div></div></form><div class="examples"><button class="example" data-action="example"><b>产品功能比较</b><span>↗</span><small>对照功能说明，区分事实与未知。</small></button><button class="example" data-action="feedback"><b>小红书口碑研究</b><span>↗</span><small>体验指定平台尚未接入时如何处理。</small></button></div><div class="start-footer"><span>结论可追溯</span><span>独立复核</span><span>可导出资料</span></div><p class="compare-hint">本方案：<b>${layout==='a'?'提交后，对话留在左边，报告在右边生成。':'提交后，依次进入进度页与完整报告页。'}</b></p></div>`}
  function progress(){return `<ol class="progress-list">${steps.map((x,i)=>`<li class="${i<state().step?'done':i===state().step?'active':''}"><i>${i<state().step?'✓':i+1}</i>${x}${i===state().step?' · 演示中':''}</li>`).join('')}</ol>`}
  function controls(){if(layout==='a')return `<div class="progress-demo">自动演示进度 · 正式流程根据真实事件更新。<button data-action="cancel">取消任务</button></div>`;return `<div class="progress-demo">手动推进演示，不产生请求。<button data-action="advance">${state().step<2?'下一阶段 →':'查看演示报告 →'}</button><button data-action="cancel">取消任务</button></div>`}
  function follow(){return `<form id="follow-form" class="follow"><label for="follow-input">${layout==='a'?'继续对话':'基于报告继续研究'}</label><textarea id="follow-input" required maxlength="800" placeholder="例如：进一步核对两款 App 的地区限制">${esc(state().follow)}</textarea><button class="solid" type="submit">${layout==='a'?'发送补充需求 ↑':'创建关联研究 →'}</button><small>仅演示后续任务入口；不会生成新的事实结论。</small></form>`}
  function report(){const s=state();return `<div class="report-head"><div class="eyebrow">RESEARCH REPORT / 演示报告</div><h1>训练计划功能对比</h1><span class="status-badge">部分完成 · 地区与版本仍待核实</span><p>App A × App B · 4 份虚构来源 · 复核状态为演示设定</p></div><nav class="report-tabs" aria-label="报告内容">${[['report','报告'],['sources','来源 4'],['review','过程与复核']].map(([id,label])=>`<button data-tab="${id}" class="${s.tab===id?'active':''}" aria-pressed="${s.tab===id}">${label}</button>`).join('')}</nav><div class="report-body">${s.skipped.length?`<div class="limit">本次未取得：${s.skipped.map(id=>cap(id).name).join("、")}。下方仅为公开网页固定样例，不包含这些平台的观点。</div>`:""}${s.tab==='sources'?sourceList():s.tab==='review'?reviews():body()}</div><div class="exports"><button class="outline" data-export="md">↓ 导出演示 Markdown</button><button class="outline" data-export="csv">↓ 导出演示 CSV</button></div>`}
  function body(){return `<section><h2><span class="section-number">01</span>主要发现</h2><p>两款 App 的说明均提到训练计划入口。App A 明确描述了调整每周训练日，App B 的现有资料只描述了查看安排。<button class="ref" data-source="S1">[S1]</button><button class="ref" data-source="S2">[S2]</button></p><p>因此，可以对比“说明文档写了什么”；还不能据此判断 App B 缺少调整功能。</p></section><section><h2><span class="section-number">02</span>功能与证据对照</h2><div class="table-wrap"><table><thead><tr><th>研究项</th><th>App A</th><th>App B</th></tr></thead><tbody><tr><td>训练计划入口</td><td>有说明 <button class="ref" data-source="S1">S1</button></td><td>有说明 <button class="ref" data-source="S2">S2</button></td></tr><tr><td>调整训练日</td><td>明确描述</td><td>资料未说明</td></tr><tr><td>地区与版本</td><td>具体范围未知</td><td>具体范围未知</td></tr></tbody></table></div></section><section><h2><span class="section-number">03</span>下一步值得核对什么</h2><p>补查 App B 的计划设置说明，并在当前客户端核对操作入口。优先确认功能是否存在，再判断是否值得提出改进建议。</p></section><div class="limit">资料没有提到某项功能，不等于该功能不存在。以上 App、原文及复核记录全部虚构，仅用于体验布局。</div>`}
  function sourceList(){return `<h2>查看每条结论的来处</h2><p class="dialog-hint">本例：公开网页 4 份。将来按平台、正文/评论/字幕、日期和取得状态筛选；笔记数与作者数分别统计。</p>${Object.entries(sources).map(([id,x])=>`<div class="source-row"><span class="source-index">${id}</span><button data-source="${id}">${x.title}<small>虚构资料 · 日期未知 · 点击展开原文</small></button><span>↗</span></div>`).join('')}`}
  function reviews(){return `<h2>复核如何改变了报告</h2><div class="review-event"><b>分析初稿</b><small>将“未在资料中发现”写成“App B 不支持调整训练日”。</small></div><div class="review-event"><b>独立复核 · 发现推断过度</b><small>现有证据不足以证明功能不存在，要求改为未知。</small></div><div class="review-event"><b>修正一次</b><small>改为“资料未说明”，保留地区与版本限制。</small></div><div class="review-event"><b>演示复核状态：修正后通过</b><small>范围仍为部分完成。此处是预设交互情境，没有真实模型调用。</small></div><div class="limit">模拟通过仅用于展示状态，不能作为模型质量或准确率的证明。</div>`}
  function split(){const s=state();return `<div class="split"><section class="conversation" aria-label="需求与对话"><span class="eyebrow">你的研究任务</span><div class="user-message">${esc(s.question)}</div><div class="speaker"><span class="avatar">↗</span>资料助手 <span class="mock-label">演示</span></div><div class="assistant-message"><p>${s.stage==='done'?'报告已整理到右侧。一个关键区别：资料没有说明，不等于功能不存在。你可以点击引用核对，也可以继续提出需求。':s.stage==='blocked'?'你指定的平台是本次必要来源，需要先解决接入问题。':s.stage==='cancelled'?'演示任务已取消。当前输入保留，可以重新开始。':'我会先对照两款 App 的功能说明，再核对引用、日期与适用条件。当前展示固定演示任务。'}</p>${s.region||s.period?`<p class="dialog-hint">范围：${esc(s.region||'地区不限')} · ${esc(s.period||'时间不限')}</p>`:''}</div>${acquisitionStatus()}${s.stage==='blocked'?blocked():''}${s.stage==='running'?`<div class="process-box">${progress()}${controls()}</div>`:''}${s.stage==='blocked'?'':s.stage==='cancelled'?'<button class="outline" data-action="restart">重新开始演示</button>':follow()}</section><section class="report-space" aria-label="报告">${s.stage==='done'?report():`<div class="empty-report"><div><div class="document-symbol">▤</div><h2>${s.stage==='blocked'?'等待必需资料':s.stage==='cancelled'?'任务已取消':'报告将在这里呈现'}</h2><p>${s.stage==='blocked'?'未获取小红书等必要来源时，不生成冒充其评价的报告。':s.stage==='cancelled'?'没有发生搜索或模型调用。':'左侧关注研究过程，右侧阅读结果。结论生成后可直接展开原文核对。'}</p><span class="eyebrow">REPORT CANVAS</span></div></div>`}</section></div>`}
  function staged(){const s=state();return `<div class="stage-page"><div class="stepper"><span>01 提出问题</span><span class="line"></span><span class="${s.stage!=='done'?'current':''}">02 研究过程</span><span class="line"></span><span class="${s.stage==='done'?'current':''}">03 阅读报告</span></div>${s.stage==='done'?`<div class="report-controls"><span class="eyebrow">研究已结束 / 演示</span><button class="text-button" data-action="back-progress">← 返回过程</button></div><article class="report-space">${report()}${follow()}</article>`:s.stage==='cancelled'?`<h1>任务已取消</h1><p class="subtitle">输入已保留，本次没有发生任何外部调用。</p><button class="solid" data-action="restart">重新开始演示</button>`:`<div class="eyebrow">RESEARCH IN PROGRESS</div><h1>正在把资料，整理成答案。</h1><p class="subtitle">${esc(s.question)}</p><div class="research-card"><h2>${steps[s.step]}</h2><p>此处使用手动进度演示，你可以检查每个阶段的呈现方式。</p>${progress()}${controls()}</div><details><summary class="dialog-hint">查看研究范围与来源计划</summary><p class="dialog-hint">地区：${esc(s.region||'不限')} · 时间：${esc(s.period||'不限')}。对照 4 份虚构功能说明，保留未知项。真实产品将根据实际事件更新状态。</p></details>`}</div>`}
  function render(){$('capability-count').textContent=capabilityCatalog.length;document.querySelectorAll('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===layout)));$('main').innerHTML=top()+(libraryOpen?library():state().stage==='input'?input():layout==='a'?split():state().stage==='blocked'?`<div class="stage-page">${acquisitionStatus()}${blocked()}</div>`:staged());document.title=`方案 ${layout.toUpperCase()} · 资料助手交互草稿`;}
  function saveInputs(){const s=state();if($('question'))s.question=$('question').value;if($('region'))s.region=$('region').value;if($('period'))s.period=$('period').value;if($('follow-input'))s.follow=$('follow-input').value}
  function start(){const s=state();clearTimeout(runTimer);libraryOpen=false;
    if(s.routing==='auto'){s.selected=['web'];s.required=['web'];if(/小红书/.test(s.question)){s.selected.push('xhs');s.required.push('xhs');}}
    if(!s.selected.length){toast('请至少选择一个资料来源');return}
    s.skipped=s.selected.filter(id=>!cap(id).ready&&!s.required.includes(id));
    const missing=s.selected.some(id=>s.required.includes(id)&&!cap(id).ready);
    if(!missing&&!s.selected.some(id=>cap(id).ready)){toast('没有可用的演示来源，请调整资料范围');return}
    s.stage=missing?'blocked':'running';s.step=0;render();scheduleDemo();}
  function evidence(id){const x=sources[id];if(!x)return;$('evidence-content').innerHTML=`<span class="status-badge">${id} · 虚构演示来源</span><h2 id="evidence-title">${x.title}</h2><p class="dialog-hint">与结论对应的支持片段</p><blockquote>${x.quote}</blockquote><dl><dt>发布日期</dt><dd>${x.date}</dd><dt>适用版本</dt><dd>${x.version}</dd><dt>原始网址</dt><dd>虚构来源，无外部链接</dd><dt>证据编号</dt><dd>${id}</dd></dl><div class="limit">这里让你核对“结论有没有被原文支持”。正式产品将展示实际采集信息。</div>`;$('evidence').showModal()}
  function download(kind){const rows=[['record_type','review_status','question','content','source_ids'],['demo','simulated_pass','演示任务：App A 与 App B 功能对比','两款资料均提到训练计划入口','S1;S2'],['demo','simulated_pass','演示任务：App A 与 App B 功能对比','App B 是否支持调整训练日未知','S2']];const missing=state().skipped.map(id=>cap(id).name).join('；');rows.forEach((row,i)=>row.push(i===0?'missing_sources':missing));const text=kind==='md'?(missing?'未取得来源：'+missing+'。本文件不包含其平台观点。\n\n':'')+'# 训练计划功能对比（演示）\n\n全部资料及复核为虚构，不是真实研究结果。\n\n- 两款说明均提及训练计划入口。[S1][S2]\n- App A 说明可调整训练日；App B 的资料未说明，不能认定功能不存在。\n- 地区与版本范围未知。\n\n## 来源（虚构）\n'+Object.entries(sources).map(([id,x])=>`- ${id} ${x.title}：${x.quote}`).join('\n'):'\ufeff'+rows.map(row=>row.map(x=>'"'+x.replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:kind==='md'?'text/markdown;charset=utf-8':'text/csv;charset=utf-8'}));a.href=url;a.download=`demo-research.${kind}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已下载带“演示”标识的样例文件')}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){b.closest('dialog').close();return}if(b.dataset.layout){saveInputs();clearTimeout(runTimer);libraryOpen=false;layout=b.dataset.layout;history.replaceState(null,'',`?layout=${layout}`);render();scheduleDemo();return}if(b.dataset.source){evidence(b.dataset.source);return}if(b.dataset.tab){saveInputs();state().tab=b.dataset.tab;render();return}if(b.dataset.export){download(b.dataset.export);return}if(b.dataset.route){state().routing=b.dataset.route;if(b.dataset.route==='auto'){state().selected=['web'];state().required=['web']}drawPicker();return}
  if(b.dataset.group){catalogGroup=b.dataset.group;render();return}
  if(b.dataset.capability){const x=cap(b.dataset.capability);info(x.name+' · 能力详情',`<p>${x.purpose}</p><ul>${x.ops.map(op=>`<li>${op}：${x.ready?'固定样例演示，未执行检测':'尚未接入本产品'}</li>`).join('')}</ul><p>${x.auth||'接入后按具体操作验证可用性。'}</p><p>后端将记录每项操作的支持情况、登录状态、最近验证时间与失败原因。本页不执行安装或登录。</p>`);return}
  switch(b.dataset.action){case 'return-task':libraryOpen=false;render();scheduleDemo();break;case 'catalog':saveInputs();clearTimeout(runTimer);if($('source-picker').open)$('source-picker').close();libraryOpen=true;render();break;
  case 'apply-sources':{if(!state().selected.length){toast('请至少选择一个来源');break}const stage=state().stage;pickerBackup=null;$('source-picker').close();if(stage==='blocked'||stage==='running')start();else{if(stage==='done')state().stage='input';render()}break}
  case 'feedback':$('question').value='查看小红书用户对 App A 训练计划的评价，结合官网功能说明整理问题';state().routing='manual';state().selected=['web','xhs'];state().required=['xhs'];saveInputs();render();break;case 'scope':{const hidden=!$('scope-fields').hidden;$('scope-fields').hidden=hidden;b.setAttribute('aria-expanded',String(!hidden));break}case 'sources':openPicker();break;case 'example':$('question').value=example;break;case 'links':$('question').value='请整理我指定的产品帮助文档，比较功能和适用条件';toast('可以体验输入方式；此草稿仍展示同一份固定样例');break;case 'jump':saveInputs();clearTimeout(runTimer);libraryOpen=false;state().question=example;state().selected=['web'];state().required=['web'];state().skipped=[];state().stage='done';state().step=4;render();break;case 'advance':saveInputs();state().step++;if(state().step>=3){state().stage='done';state().step=4}render();break;case 'cancel':clearTimeout(runTimer);saveInputs();state().stage='cancelled';render();break;case 'restart':start();break;case 'back-progress':state().stage='running';state().step=2;render();break}});
  document.addEventListener('submit',e=>{if(e.target.id==='research-form'){e.preventDefault();saveInputs();if(state().question.trim())start()}if(e.target.id==='follow-form'){e.preventDefault();saveInputs();info('后续研究已接收（演示）',`<p>你的补充需求：</p><p><b>${esc(state().follow)}</b></p><p>正式产品会判断范围变化，并创建关联任务、保留旧报告。本草稿不执行新任务，当前报告内容保持不变。</p>`)}});
  $('new-task').onclick=()=>{saveInputs();clearTimeout(runTimer);libraryOpen=false;state().stage='input';render()};$('history').onclick=()=>{saveInputs();clearTimeout(runTimer);libraryOpen=false;state().question=example;state().selected=['web'];state().required=['web'];state().skipped=[];state().stage='done';state().step=4;render()};
  $('help').onclick=()=>info('用同一个任务，比较两种体验', '<p><b>A：对话＋报告。</b>需求始终留在左边，结果在右边；适合边阅读边追问。</p><p><b>B：分阶段研究。</b>输入、进度、报告依次出现；适合一次提出需求，专注阅读完整报告。</p><ul><li>A 点击开始后自动演示；B 保留手动推进，方便对比。</li><li>结果中点击 S1、切换来源和复核、尝试导出。</li><li>顶部切换 A/B，各自保留当前演示进度。</li></ul><p>两套使用相同资料和视觉风格，优先比较操作和布局。没有真实搜索或模型调用。</p>');
  $('source-settings').onclick=()=>{saveInputs();clearTimeout(runTimer);libraryOpen=true;render()};
  $('model-settings').onclick=()=>info('运行设置', '<p>正式产品将在这里设置分析与复核模型、调用上限及本机配置。</p><p>当前仅体验布局，不读取、输入或保存 API 密钥。</p>');
  document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
  $('source-picker').addEventListener('close',()=>{if(pickerBackup){Object.assign(state(),pickerBackup);pickerBackup=null;if(!libraryOpen)render();scheduleDemo()}});
  document.addEventListener('change',e=>{if(e.target.dataset.pick){const id=e.target.dataset.pick;state().routing='manual';if(e.target.checked){state().selected.push(id);state().required.push(id)}else{state().selected=state().selected.filter(x=>x!==id);state().required=state().required.filter(x=>x!==id)}drawPicker()}if(e.target.dataset.required){const id=e.target.dataset.required;state().required=state().required.filter(x=>x!==id);if(e.target.checked)state().required.push(id)}});
  document.addEventListener('input',e=>{if(e.target.id==='picker-query'){document.querySelectorAll('[data-pick-row]').forEach(row=>row.hidden=!row.dataset.pickRow.toLowerCase().includes(e.target.value.toLowerCase()))}if(e.target.id==='catalog-query'){catalogQuery=e.target.value;$('catalog-results').innerHTML=catalogCards()}});
  render();
})();
