(() => {
  let csrf=''; const $=id=>document.getElementById(id);
  const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const statusLabel=s=>({running:'处理中',completed:'已完成',stopped:'已停止',interrupted:'已中断',failed:'运行失败'})[s]||s;
  const statusClass=s=>s==='completed'?'done':(s==='stopped'||s==='failed'||s==='interrupted'?'stop':'');
  const sessionToken=document.body.dataset.session||'';
  async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Accept':'application/json','X-CSRF-Token':csrf,'X-Session-Token':sessionToken,...(options.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.error||'请求失败');return data}
  function showNotice(text){$('notice').textContent=text;$('notice').classList.remove('hidden')}
  function renderPlan(plan){$('plan-result').classList.remove('hidden');$('acquisition-result').classList.add('hidden');$('plan-result').innerHTML=`<h3>研究计划预览</h3><p>${escapeHtml(plan.notice)}</p><div class="facts">${plan.input.region?`<span class="fact">地区：${escapeHtml(plan.input.region)}</span>`:''}${plan.input.period?`<span class="fact">时间：${escapeHtml(plan.input.period)}</span>`:''}<span class="fact">来源：公开网页</span></div><ol>${plan.steps.map(s=>`<li><b>${escapeHtml(s.title)}</b> · ${escapeHtml(s.owner)}：${escapeHtml(s.output)}</li>`).join('')}</ol><p class="muted">尚未接入：${plan.not_connected.map(escapeHtml).join('、')}。确认范围后，下一步可以获取公开网页候选。</p><button class="primary" id="confirm-acquisition" type="button">确认计划并获取公开网页</button>`;$('confirm-acquisition').addEventListener('click',()=>startAcquisition(plan.input,$('confirm-acquisition')))}
  function renderAcquisition(d){
    const run=d.run||{}, evidence=d.evidence||{};
    $('acquisition-result').classList.remove('hidden');
    const fetched=(d.records||[]).filter(r=>r.status==='fetched_unverified').length;
    const rows=(d.candidates||[]).map(c=>{const record=(d.records||[]).find(x=>x.search_rank===c.rank)||{};
      return `<li><b>S${escapeHtml(c.rank)} · ${escapeHtml(c.title||'未命名页面')}</b><br><a href="${escapeHtml(c.url)}" target="_blank" rel="noreferrer">${escapeHtml(c.url)}</a><span class="muted"> · ${escapeHtml(record.status||'未读取')}</span></li>`}).join('');
    $('acquisition-result').innerHTML=`<h3>公开网页获取结果</h3><p>${escapeHtml(run.input?.question||'')}</p><p>${run.status==='running'?'正在搜索或读取页面，不调用模型。':`采集流程${escapeHtml(statusLabel(run.status))}，取得 ${fetched} 份正文。`}</p>${run.error?`<div class="notice">${escapeHtml(run.error.message)}</div>`:''}<ol>${rows}</ol><p class="muted">取得正文不代表符合时间、地区范围，也不代表复核通过。</p>${run.status==='completed'?'<button id="prepare-evidence" class="primary">准备分析资料（不调用模型）</button>':''}<div id="evidence-preview"></div>`;
    if($('prepare-evidence')) $('prepare-evidence').addEventListener('click',async()=>{const b=$('prepare-evidence');b.disabled=true;try{renderEvidence(await api('/api/acquisitions/'+run.id+'/prepare',{method:'POST',headers:{'Content-Type':'application/json','Origin':location.origin},body:'{}'}))}catch(e){showNotice(e.message)}finally{b.disabled=false}});
    renderEvidence(evidence);
  }
  function renderEvidence(e){
    if(e.status==='not_prepared'||!e.status)return;
    if(e.status==='blocked'){$('evidence-preview').innerHTML=`<p class="notice">${escapeHtml(e.message)}</p>`;return}
    const c=e.case, budget=e.preflight.budget_status;
    $('evidence-preview').innerHTML=`<h3>分析输入已准备 · 分析与复核均未执行</h3><p>纳入 ${c.sources.length} 份完整正文，${e.input_bytes} 字节。${budget==='new_budget_required'?'尚未配置本轮模型试测预算。':`预算预检：${escapeHtml(budget)}`}</p><p>范围：${escapeHtml(c.web_context.region||'未指定地区')} · ${escapeHtml(c.web_context.period||'未指定时间')}</p><ul>${c.web_context.limitations.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><h4>交给分析角色的问题</h4><ol>${Object.values(c.questions).map(q=>`<li>${escapeHtml(q)}</li>`).join('')}</ol>${c.sources.map(s=>`<details><summary>${escapeHtml(s.source_id)} · ${escapeHtml(s.title)} · 查看保存原文</summary><p>采集：${escapeHtml(s.fetched_at)}；发布日期未核实；地区与时间范围待核实。</p><p>搜索日期提示：${escapeHtml(s.search_published_hint||'未知')}（不可当作已核实日期）</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${escapeHtml(s.content)}</pre></details>`).join('')}<p>未纳入：${escapeHtml(c.web_context.excluded_sources.map(s=>s.source_id+' '+s.reason).join('；')||'无')}</p><button id="handoff-preview" class="primary">查看角色调用预览（不调用模型）</button><div id="handoff-result"></div>`;
    $('handoff-preview').addEventListener('click',async()=>{const b=$('handoff-preview');b.disabled=true;try{renderHandoff(await api('/api/acquisitions/'+c.web_context.acquisition_id+'/handoff-preview',{method:'POST',headers:{'Content-Type':'application/json','Origin':location.origin},body:'{}'}))}catch(err){showNotice(err.message)}finally{b.disabled=false}});
  }
  function renderHandoff(d){if(d.status!=='preview_only'){$('handoff-result').innerHTML=`<p class="notice">${escapeHtml(d.message||'请先准备分析资料')}</p>`;return}const rows=d.roles.map(r=>`<li><b>${escapeHtml(r.owner)}</b> · ${escapeHtml(r.model_route)} · <span class="status">${escapeHtml(r.status)}</span><br><span class="muted">输入：${escapeHtml(JSON.stringify(r.input))}</span><br>输出：${escapeHtml(r.output)}</li>`).join('');$('handoff-result').innerHTML=`<h4>角色调用顺序（预览）</h4><p>${escapeHtml(d.notice)} 当前至少需要 ${d.limits.required_calls_before_delivery} 次调用；修正最多 ${d.limits.repair_calls_max} 次。预览调用数：${d.api_calls}。</p><ol>${rows}</ol><p class="muted">分析完成后才会创建复核输入；只有复核返回 revise 才会创建修正输入。当前预算状态：${escapeHtml(d.budget_status)}。</p>`}
  async function refreshAcquisitions(){try{const list=await api('/api/acquisitions');$('acquisition-history').innerHTML=list.map(t=>`<div class="task-row"><div><h3>${escapeHtml(t.input.question)}</h3><p>${new Date(t.created_at).toLocaleString()} · ${escapeHtml(statusLabel(t.status))}</p></div><button class="ghost" data-acquisition="${escapeHtml(t.id)}">查看采集资料</button></div>`).join('')||'<p>暂无采集记录。</p>';document.querySelectorAll('[data-acquisition]').forEach(b=>b.addEventListener('click',async()=>{try{renderAcquisition(await api('/api/acquisitions/'+b.dataset.acquisition));$('acquisition-result').scrollIntoView({behavior:'smooth'})}catch(e){showNotice(e.message)}}))}catch(e){showNotice(e.message)}}
  async function startAcquisition(input,button){button.disabled=true;showNotice('已确认计划，正在获取公开网页；页面不会调用模型。');try{const run=await api('/api/acquisitions',{method:'POST',headers:{'Content-Type':'application/json','Origin':location.origin},body:JSON.stringify({...input,request_id:crypto.randomUUID()})});await watchAcquisition(run.id)}catch(e){showNotice(e.message);button.disabled=false}}
  async function watchAcquisition(id){for(let i=0;i<90;i++){const d=await api('/api/acquisitions/'+id);renderAcquisition(d);if(d.run.status!=='running'){await refreshAcquisitions();return}await new Promise(r=>setTimeout(r,1000))}showNotice('网页获取仍在运行，请稍后刷新；没有重复启动任务。')}
  function facts(f){return `<span class="fact">纳入 ${f.included_notes} 条笔记</span><span class="fact">已知作者 ${f.known_unique_authors} 名</span>${f.same_author_groups.length?'<span class="fact">同作者已标记</span>':''}`}
  function renderScenarios(list){$('scenarios').innerHTML=list.map(s=>`<article class="scenario"><div><span class="eyebrow">离线回放</span><h3>${escapeHtml(s.title)}</h3></div><p>${escapeHtml(s.description)}<br><span class="muted">${escapeHtml(s.question)}</span></p><div class="facts">${facts(s.sampling_facts)}</div><button class="primary" data-start="${s.id}">运行回放</button></article>`).join('');document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.start,b)))}
  async function start(id,button){button.disabled=true;showNotice('正在运行离线回放，页面会自动刷新任务状态。');try{const task=await api('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json','Origin':location.origin},body:JSON.stringify({scenario_id:id,request_id:crypto.randomUUID()})});await refresh();await watch(task.id)}catch(e){showNotice(e.message);button.disabled=false}}
  async function watch(id){for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,220));const d=await api('/api/tasks/'+id);await renderDetail(d);if(d.task.status!=='running'){await refresh();return} }showNotice('任务仍在运行，请点击刷新查看；本机任务未被重复启动。')}
  async function refresh(){try{const list=await api('/api/tasks');$('tasks').innerHTML=list.length?list.map(t=>`<div class="task-row"><div><h3>${escapeHtml(t.title)}</h3><p>${new Date(t.created_at).toLocaleString()} · ${escapeHtml(t.last_action||'已创建')}</p></div><div><span class="status ${statusClass(t.status)}">${statusLabel(t.status)}</span> <button class="ghost" data-open="${t.id}">查看</button></div></div>`).join(''):'<p class="muted">还没有回放任务。</p>';document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openTask(b.dataset.open)))}catch(e){showNotice(e.message)}}
  function renderDetail(d){
    const s=d.state||{},draft=s.final_draft||{},answers=draft.answers||[],hyps=draft.hypotheses||[];
    const answerHtml=answers.map(a=>{const refs=(a.refs||[]).map(r=>`<li><b>${escapeHtml(r.source_id)}</b> · ${escapeHtml(r.quote)} <span>（${escapeHtml(r.locator)}）</span></li>`).join('');return `<div class="answer"><span class="status">${escapeHtml(a.question_id)} · ${escapeHtml(a.status)}</span><p>${escapeHtml(a.text)}</p><ul class="refs">${refs}</ul></div>`}).join('')||'<p class="muted">尚未生成可显示的草稿。</p>';
    const hypHtml=hyps.length?`<h3>待验证假设</h3>${hyps.map((h,i)=>`<div class="hypothesis"><b>H${i+1} · ${escapeHtml(h.text)}</b><p>替代解释：${escapeHtml(h.alternative)}</p><p>下一步：${escapeHtml(h.next_action)}</p></div>`).join('')}`:'';
    const stop=s.stop_reason?`<div class="notice">停止原因：${escapeHtml(s.stop_reason)}</div>`:'';
    const actions=d.task.status!=='running'?`<a href="/api/tasks/${d.task.id}/report.md">下载 Markdown</a><a href="/api/tasks/${d.task.id}/materials.csv">下载 CSV</a>`:'';
    const coverage=s.coverage||{answered:[],unknown:[],omitted:[]};
    $('detail').classList.remove('hidden');
    $('detail').innerHTML=`<div class="section-head"><div><span class="eyebrow">任务详情 · ${escapeHtml(d.task.mode)}</span><h2>${escapeHtml(d.task.title)}</h2><p class="muted">${escapeHtml(d.task.question)}</p></div><span class="status ${statusClass(d.task.status)}">${statusLabel(d.task.status)}</span></div><div class="meta"><span class="tag">复核：${escapeHtml(s.review_status||'未运行')}</span><span class="tag">版本：${s.revision||0}/1</span><span class="tag">模拟调用：${s.simulated_calls||0}</span><span class="tag">覆盖：回答 ${coverage.answered.length} · 未知 ${coverage.unknown.length} · 遗漏 ${coverage.omitted.length}</span></div>${stop}<div class="result-actions">${actions}</div><h3>结论</h3>${answerHtml}${hypHtml}<h3>来源与限制</h3><p>本页面只显示结构化证据。纳入 ${d.case.sampling_facts.included_notes} 条笔记，来自 ${d.case.sampling_facts.known_unique_authors} 名已知作者；同作者：${escapeHtml(d.case.sampling_facts.same_author_groups.map(g=>g.join('、')).join('；')||'无')}。总体发生率保持未知。</p>`;
  }
  async function openTask(id){try{await renderDetail(await api('/api/tasks/'+id));$('detail').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){showNotice(e.message)}}
  async function bootstrap(){try{const d=await api('/api/bootstrap');csrf=d.csrf;renderScenarios(d.scenarios);$('quota').textContent=d.live_execution_enabled?'可执行':'真实调用未开放 · 预算需单独配置';await refresh();await refreshAcquisitions()}catch(e){showNotice(e.message)}}
  $('refresh-acquisitions').addEventListener('click',refreshAcquisitions);
  $('refresh').addEventListener('click',refresh);
  $('plan-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const sources=[...document.querySelectorAll('input[name="source"]:checked')].map(x=>x.value);renderPlan(await api('/api/plan-preview',{method:'POST',headers:{'Content-Type':'application/json','Origin':location.origin},body:JSON.stringify({question:$('question').value,region:$('region').value,period:$('period').value,sources})}))}catch(err){showNotice(err.message)}finally{button.disabled=false}});
  bootstrap();
})();
